### ISSUE TITLE
More Documentation Needed

### ISSUE THREAD

**Issue by bscuron** [cis3296f22/GameMaster#17]
I was able to add the discord bot to the discord channel. However, the games listed in the README were not working for me when trying to run a game from the chat. The only game that I was listed in the autocompletion of commands was 'connect4'. I tried to run the 'connect4' game, but I had trouble getting the game to start. If possible, please add more documentation to the README. More instructions would be useful for someone, like me, that is not familiar with using discord bots.

**Comment by jay-newman** [comment]
Bot is now live on Heroku. Adding bot to server is just the click of a link. Readme is updated for correct slash commands and on main bot.
